apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portal-monitor-state
  namespace: portal-monitor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 1Gi